### ISSUE TITLE
Different chances of drop by permission

### ISSUE THREAD

**Issue by SrBedrock** [MrButtersDEV/SilkySpawnersLITE#7]
**Is your feature request related to a problem? Please describe.**
I would like to add different drop chances according to player permission, that would allow changing chance according to world and other variables.

**Describe the solution you'd like**
Option in the configuration where it is possible to add a permission with a chance to drop.

**Comment by MrButtersDEV** [comment]
I plan on doing a permissions overhaul which will add this and #3
