### ISSUE TITLE
Permission Based Bypass for Spawner Cost + Group System

### ISSUE THREAD

**Issue by xYosemite** [MrButtersDEV/SilkySpawnersLITE#8]
Is your feature request related to a problem? Please describe.
Depends on how you look at it, it's not a bug per say but something probably needed for the plugin, so you have the option to price the mining of spawners but no permission to bypass the price, i was wondering if this could be an addition? 

Furthermore you could make it so you can charge different groups different prices in the config.
e.g.  VIP group can silk a spawner for 10k while default is 20k. VIP+ can silk for 5k.

Describe the solution you'd like
just a silkyspawners.cost.bypass permission or something.

Describe alternatives you've considered
there are none, i cant seem to find a solution to this as nothing else is updated and this plugin is the best one out right now

Additional context
none.

**Comment by MrButtersDEV** [comment]
Added
